# Generated by Django 4.2.4 on 2023-09-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api_project', '0002_restaurant_restaurant__restaur_416e32_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
