# Generated by Django 4.2.4 on 2023-09-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api_project', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='categories',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
