# Generated by Django 4.2.4 on 2023-09-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api_project', '0004_alter_restaurant_address_alter_restaurant_categories_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
