# Generated by Django 4.2.4 on 2023-09-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api_project', '0004_alter_restaurant_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
