# Generated by Django 4.2.4 on 2023-09-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api_project', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='geometry',
        ),
    ]
