# Generated by Django 4.2.4 on 2023-09-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api_project', '0005_alter_review_rating_alter_review_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
