# Generated by Django 4.2.4 on 2023-09-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api_project', '0005_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=512)),
                ('restaurant_id', models.CharField(max_length=512)),
                ('stars', models.DecimalField(decimal_places=1, max_digits=3)),
                ('text', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
