# Generated by Django 4.2.4 on 2023-09-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api_project', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=512, primary_key=True, serialize=False),
        ),
    ]
