# Generated by Django 4.2.4 on 2023-09-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api_project', '0007_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
    ]
