# Generated by Django 4.2.4 on 2023-09-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api_project', '0007_remove_review_geometry'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['restaurant_id'], name='restaurant__restaur_416e32_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_id'], name='restaurant__user_id_a0214e_idx'),
        ),
    ]
