# Generated by Django 4.2.4 on 2023-09-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api_project', '0008_remove_user_registration_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
