# Generated by Django 4.2.4 on 2023-09-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api_project', '0009_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
    ]
