# Generated by Django 4.2.4 on 2023-09-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant_api_project', '0011_delete_restaurant_delete_review_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review_count', models.IntegerField()),
                ('categories', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=512)),
                ('restaurant_id', models.CharField(max_length=512)),
                ('stars', models.DecimalField(decimal_places=1, max_digits=3)),
                ('text', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
    ]
